#!name=懒人听书

#!desc=懒人听书 解锁vip

#!author= WeiGiegie







[MITM]

hostname = %APPEND% shapi.mting.info,shapi.lanrentingshu.com,gzapi.lanrentingshu.com,shapi.mting.info:443



[Script]

懒人听书=type=http-response,pattern=^https?:\/\/(shapi|gzapi).(mting.info|lanrentingshu.com)\/(yyting\/userclient\/ClientGetUserInfo|lrts\/cgi\/login\/accountLogin),requires-body=1,script-path=https://raw.githubusercontent.com/WeiGiegie/666/main/lrts.js
